// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiJNmQJkarZsT8-CcMZODJQsR0ahE12Qw',
    appId: '1:710186488655:web:d559ac07f756f0ff092b3a',
    messagingSenderId: '710186488655',
    projectId: 'smart-library-6f30e',
    authDomain: 'smart-library-6f30e.firebaseapp.com',
    storageBucket: 'smart-library-6f30e.firebasestorage.app',
    measurementId: 'G-VQH7P63HY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIlolNDhDbBbSzFzGhrpQoiErjeb1KX7c',
    appId: '1:710186488655:android:1811e279fb44e53a092b3a',
    messagingSenderId: '710186488655',
    projectId: 'smart-library-6f30e',
    storageBucket: 'smart-library-6f30e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBS4HSfxc6wF8G1culevhUSrRC_m0T_ew',
    appId: '1:710186488655:ios:ba54459d7b6b83d6092b3a',
    messagingSenderId: '710186488655',
    projectId: 'smart-library-6f30e',
    storageBucket: 'smart-library-6f30e.firebasestorage.app',
    iosBundleId: 'com.example.smartLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBS4HSfxc6wF8G1culevhUSrRC_m0T_ew',
    appId: '1:710186488655:ios:ba54459d7b6b83d6092b3a',
    messagingSenderId: '710186488655',
    projectId: 'smart-library-6f30e',
    storageBucket: 'smart-library-6f30e.firebasestorage.app',
    iosBundleId: 'com.example.smartLibrary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiJNmQJkarZsT8-CcMZODJQsR0ahE12Qw',
    appId: '1:710186488655:web:001f599600a1e552092b3a',
    messagingSenderId: '710186488655',
    projectId: 'smart-library-6f30e',
    authDomain: 'smart-library-6f30e.firebaseapp.com',
    storageBucket: 'smart-library-6f30e.firebasestorage.app',
    measurementId: 'G-S9JD3V4HLB',
  );

}